name: Build and Run Java with Javac (Java 11 Test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compile Java files with Java 11 compatibility
      run: javac -source 11 -target 11 src/gerenciadordetarefas/*.java -d bin
