name: Build Java Project with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin' # Ou outra distribuição como 'adoptopenjdk', 'zulu', 'corretto'
    - name: Run Ant Build
      run: ant -buildfile build.xml
